import type { Node, FleetOverview, LogEntry, VersionInfo } from "./api";

export const mockOverview: FleetOverview = {
  total: 5,
  by_state: {
    healthy: 3,
    unhealthy: 1,
    starting_up: 1,
  },
};

export const mockNodes: Node[] = [
  {
    node_id: "val-mainnet-01",
    lifecycle_state: "healthy",
    role: "validator",
    client: "jito",
    cluster: "mainnet-beta",
    hostname: "sg-node-01",
    ip_address: "192.168.1.101",
    agent_version: "1.2.0",
    last_seen_at: Date.now() / 1000 - 5,
    registered_at: Date.now() / 1000 - 86400 * 30,
    live_status: {
      state: "healthy",
      local_slot: 213456789,
      reference_slot: 213456790,
      slots_behind: 1,
      healthy: true,
      restart_count: 0,
      crash_looping: false,
      version: "1.17.20",
      role: "validator",
      client: "jito",
      cluster: "mainnet-beta",
      cpu_usage_percent: 45.2,
      memory_used_bytes: 128 * 1024 * 1024 * 1024,
      memory_total_bytes: 256 * 1024 * 1024 * 1024,
      disk_used_bytes: 1024 * 1024 * 1024 * 1024,
      disk_total_bytes: 2048 * 1024 * 1024 * 1024,
      updated_at_unix_secs: Date.now() / 1000 - 5,
      state_duration_secs: 86400 * 15,
      hostname: "sg-node-01",
    },
  },
  {
    node_id: "rpc-devnet-02",
    lifecycle_state: "unhealthy",
    role: "rpc",
    client: "agave",
    cluster: "devnet",
    hostname: "eu-rpc-02",
    ip_address: "10.0.0.50",
    agent_version: "1.1.9",
    last_seen_at: Date.now() / 1000 - 120,
    registered_at: Date.now() / 1000 - 86400 * 10,
    live_status: {
      state: "unhealthy",
      local_slot: 213000000,
      reference_slot: 213456790,
      slots_behind: 456790,
      healthy: false,
      restart_count: 3,
      crash_looping: true,
      version: "1.17.15",
      role: "rpc",
      client: "agave",
      cluster: "devnet",
      cpu_usage_percent: 98.5,
      memory_used_bytes: 250 * 1024 * 1024 * 1024,
      memory_total_bytes: 256 * 1024 * 1024 * 1024,
      disk_used_bytes: 1900 * 1024 * 1024 * 1024,
      disk_total_bytes: 2048 * 1024 * 1024 * 1024,
      updated_at_unix_secs: Date.now() / 1000 - 120,
      state_duration_secs: 3600,
      hostname: "eu-rpc-02",
    },
  },
  {
    node_id: "val-testnet-03",
    lifecycle_state: "starting_up",
    role: "validator",
    client: "firedancer",
    cluster: "testnet",
    hostname: "us-node-03",
    ip_address: "172.16.0.10",
    agent_version: "1.2.0",
    last_seen_at: Date.now() / 1000 - 2,
    registered_at: Date.now() / 1000 - 86400,
    live_status: {
      state: "starting_up",
      local_slot: 0,
      reference_slot: 213456790,
      slots_behind: 0,
      healthy: false,
      restart_count: 0,
      crash_looping: false,
      version: "0.1.0",
      role: "validator",
      client: "firedancer",
      cluster: "testnet",
      cpu_usage_percent: 15.0,
      memory_used_bytes: 16 * 1024 * 1024 * 1024,
      memory_total_bytes: 256 * 1024 * 1024 * 1024,
      disk_used_bytes: 50 * 1024 * 1024 * 1024,
      disk_total_bytes: 2048 * 1024 * 1024 * 1024,
      updated_at_unix_secs: Date.now() / 1000 - 2,
      state_duration_secs: 300,
      hostname: "us-node-03",
    },
  },
];

export const mockLogs: LogEntry[] = [
  {
    id: 1,
    service: "validator",
    level: "info",
    message: "Starting validator node with config from /etc/pillar/config.json",
    timestamp_ms: Date.now() - 50000,
  },
  {
    id: 2,
    service: "validator",
    level: "info",
    message: "Loaded identity keypair successfully",
    timestamp_ms: Date.now() - 48000,
  },
  {
    id: 3,
    service: "validator",
    level: "warn",
    message: "Slow network response when contacting gossip entrypoint",
    timestamp_ms: Date.now() - 35000,
  },
  {
    id: 4,
    service: "agent",
    level: "info",
    message: "Agent v1.2.0 started, checking in with controller",
    timestamp_ms: Date.now() - 60000,
  },
  {
    id: 5,
    service: "controller",
    level: "info",
    message: "Provision request received for node",
    timestamp_ms: Date.now() - 120000,
  },
  {
    id: 6,
    service: "validator",
    level: "error",
    message: "OOM Error: Insufficient memory to load snapshot",
    timestamp_ms: Date.now() - 10000,
  },
];

export const mockVersionInfo: VersionInfo = {
  current_version: "0.1.0",
  controller_update: {
    version: "0.1.1",
    download_url: "https://example.com/download",
    sha256: "deadbeef",
    release_notes: "Bug fixes and performance improvements",
  },
  checked_at: Date.now() / 1000,
};

export const mockGrafanaSettings = {
  grafana_url: "http://localhost:3000",
};
