fn main() -> Result<(), Box<dyn std::error::Error>> {
    tonic_prost_build::configure()
        .build_server(false)
        .build_client(true)
        .extern_path(".pillar.NodeStatus", "::pillar_shared::proto::NodeStatus")
        .extern_path(
            ".pillar.ReportStatusRequest",
            "::pillar_shared::proto::ReportStatusRequest",
        )
        .extern_path(
            ".pillar.ReportStatusResponse",
            "::pillar_shared::proto::ReportStatusResponse",
        )
        .extern_path(
            ".pillar.CommandStreamRequest",
            "::pillar_shared::proto::CommandStreamRequest",
        )
        .extern_path(
            ".pillar.ControllerCommand",
            "::pillar_shared::proto::ControllerCommand",
        )
        .extern_path(
            ".pillar.RestartCommand",
            "::pillar_shared::proto::RestartCommand",
        )
        .extern_path(
            ".pillar.RecoverCommand",
            "::pillar_shared::proto::RecoverCommand",
        )
        .extern_path(
            ".pillar.UpdateConfigCommand",
            "::pillar_shared::proto::UpdateConfigCommand",
        )
        .extern_path(
            ".pillar.UpgradeCommand",
            "::pillar_shared::proto::UpgradeCommand",
        )
        .extern_path(
            ".pillar.RegisterNodeRequest",
            "::pillar_shared::proto::RegisterNodeRequest",
        )
        .extern_path(
            ".pillar.RegisterNodeResponse",
            "::pillar_shared::proto::RegisterNodeResponse",
        )
        .extern_path(
            ".pillar.UpgradeStatusRequest",
            "::pillar_shared::proto::UpgradeStatusRequest",
        )
        .extern_path(
            ".pillar.UpgradeStatusResponse",
            "::pillar_shared::proto::UpgradeStatusResponse",
        )
        .extern_path(
            ".pillar.LogBatch",
            "::pillar_shared::proto::LogBatch",
        )
        .extern_path(
            ".pillar.LogEntry",
            "::pillar_shared::proto::LogEntry",
        )
        .extern_path(
            ".pillar.LogAck",
            "::pillar_shared::proto::LogAck",
        )
        .extern_path(
            ".pillar.ProvisionCommand",
            "::pillar_shared::proto::ProvisionCommand",
        )
        .extern_path(
            ".pillar.StopCommand",
            "::pillar_shared::proto::StopCommand",
        )
        .compile_protos(&["../shared/proto/pillar.proto"], &["../shared/proto/"])?;
    Ok(())
}
